### ISSUE TITLE
Create sign up page

### ISSUE THREAD

**Issue by Stelzr** [davismann/CSCI-3308-Project#6]
Signup page with a username and password. The same form will also include a place to input current weight, activity level, and goal.

Acceptance criteria: I should be able to login If I don't have an account I should be able to click a link that will redirect me to register. Once I login, I should be redirected to the home page if I have already completed the Body goals calculation and if not to the body calculation then redirect to the home page.

**Comment by davismann** [comment]
Davis this did!
